### ISSUE TITLE
Run jbrowse-adam on Amazon AWS

### ISSUE THREAD

**Issue by gganebnyi** [FusionWorks/jbrowse-adam#20]
1. Store ref genome and aligned reads in s3
2. Run Spark cluster as described here: http://spark.apache.org/docs/latest/ec2-scripts.html
3. deploy our software on ec2 instance and test results

For AWS access please refer to me

**Comment by gganebnyi** [comment]
lets start with using 5 m4.large machines run with --spot-price 0.02

**Comment by gganebnyi** [comment]
data should be stored in Amazon S3

**Comment by antonstamov** [comment]
implemented
